vim.opt.number          = true
vim.opt.cursorline      = false
lvim.format_on_save     = true
lvim.transparent_window = true
lvim.colorscheme        = "catppuccin"
-- lvim.colorscheme        = "vscode"
vim.opt.wrap            = true
vim.opt.textwidth       = 90
vim.opt.linebreak       = true
vim.opt.wrapmargin      = 2
vim.opt.textwidth       = 90
vim.opt.relativenumber  = true
vim.opt.cursorline      = true
